### PR TITLE
Update character.json

### PR DESCRIPTION
**Pull request by vandana1499**
#4 Added a character

### CODE REVIEW

**Review by swetankraj — CHANGES_REQUESTED** [review]
@vandana1499 so far all good. Just change img to this: https://vignette.wikia.nocookie.net/dark-netflix/images/e/e1/Closeup_-_Ulrich.jpg

**Comment by vandana1499** [comment]
Hello @swetankraj , I made changes .

**Review by swetankraj — APPROVED** [review]
@vandana1499 Thank you for your contribution! All the best for Hacktoberfest!

**Comment by vandana1499** [comment]
Thank you .

**Pull request merged**
